CREATE DATABASE 'D:\LottoMetrics.FDB'
USER 'sysdba' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET UTF8;

CREATE TABLE countries (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(50) NOT NULL,
    iso_code VARCHAR(2) NOT NULL,
    region VARCHAR(50)
);

INSERT INTO countries (country_name, iso_code, region) VALUES ('Germany', 'DE', 'Europe');

CREATE TABLE lotteries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id INTEGER NOT NULL,
    lottery_name VARCHAR(50) NOT NULL,
    main_count SMALLINT NOT NULL,
    main_start SMALLINT NOT NULL,
    main_finish SMALLINT NOT NULL,
    extra_count SMALLINT DEFAULT 0,
    extra_start SMALLINT DEFAULT 0,
    extra_finish SMALLINT DEFAULT 0,
    CONSTRAINT fk_lottery_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

INSERT INTO lotteries (
    country_id, lottery_name,
    main_count, main_start, main_finish,
    extra_count, extra_start, extra_finish
)
VALUES (1, '6 aus 49', 6, 1, 49, 1, 0, 9);

CREATE TABLE draws (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lottery_id INTEGER NOT NULL,
    draw_date DATE NOT NULL,
    main_numbers VARCHAR(50) NOT NULL,
    extra_numbers VARCHAR(20),
    CONSTRAINT fk_draw_lottery FOREIGN KEY (lottery_id) REFERENCES lotteries(id)
);

CREATE TABLE draw_numbers (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id INTEGER NOT NULL,
    number SMALLINT NOT NULL,
    number_kind VARCHAR(5) NOT NULL,
    CONSTRAINT fk_number_draw FOREIGN KEY (draw_id) REFERENCES draws(id),
    CONSTRAINT chk_number_kind CHECK (number_kind IN ('main', 'extra'))
);

CREATE INDEX idx_draws_date ON draws(draw_date);
CREATE INDEX idx_draws_lottery_id ON draws(lottery_id);
CREATE INDEX idx_draw_numbers_draw_id ON draw_numbers(draw_id);
CREATE INDEX idx_draw_numbers_number ON draw_numbers(number);
CREATE INDEX idx_draw_numbers_number_kind ON draw_numbers(number_kind);

CREATE OR ALTER PROCEDURE fill_draw_numbers
AS
DECLARE VARIABLE v_draw_id INTEGER;
DECLARE VARIABLE v_main_numbers VARCHAR(50);
DECLARE VARIABLE v_extra_numbers VARCHAR(20);
DECLARE VARIABLE v_num VARCHAR(5);
DECLARE VARIABLE v_pos INTEGER;
BEGIN
  FOR SELECT id, main_numbers, extra_numbers
      FROM draws
      INTO :v_draw_id, :v_main_numbers, :v_extra_numbers
  DO
  BEGIN
    WHILE (CHAR_LENGTH(:v_main_numbers) > 0) DO
    BEGIN
      v_pos = POSITION(',' IN :v_main_numbers);
      IF (v_pos > 0) THEN
      BEGIN
        v_num = SUBSTRING(:v_main_numbers FROM 1 FOR v_pos-1);
        v_main_numbers = SUBSTRING(:v_main_numbers FROM v_pos+1);
      END
      ELSE
      BEGIN
        v_num = :v_main_numbers;
        v_main_numbers = '';
      END
      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:v_draw_id, CAST(:v_num AS SMALLINT), 'main');
    END
    IF (:v_extra_numbers IS NOT NULL AND :v_extra_numbers <> '') THEN
    BEGIN
      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:v_draw_id, CAST(:v_extra_numbers AS SMALLINT), 'extra');
    END
  END
END

create or alter procedure add_draw_numbers (
  p_draw_id integer)
as
declare variable v_main_numbers varchar(50);
declare variable v_extra_numbers varchar(20);
declare variable v_num varchar(5);
declare variable v_pos integer;
begin
  SELECT main_numbers, extra_numbers
  FROM draws
  WHERE id = :p_draw_id
  INTO :v_main_numbers, :v_extra_numbers;

  WHILE (CHAR_LENGTH(:v_main_numbers) > 0) DO
    BEGIN
      v_pos = POSITION(',' IN :v_main_numbers);
      IF (v_pos > 0) THEN
      BEGIN
        v_num = SUBSTRING(:v_main_numbers FROM 1 FOR v_pos-1);
        v_main_numbers = SUBSTRING(:v_main_numbers FROM v_pos+1);
      END
      ELSE
      BEGIN
        v_num = :v_main_numbers;
        v_main_numbers = '';
      END

      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:p_draw_id, CAST(:v_num AS SMALLINT), 'main');
    END

    IF (:v_extra_numbers IS NOT NULL AND :v_extra_numbers <> '') THEN
    BEGIN
      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:p_draw_id, CAST(:v_extra_numbers AS SMALLINT), 'extra');
    END
end

create or alter procedure add_draw (
    p_lottery_id integer,
    p_draw_date date,
    p_main_numbers varchar(50),
    p_extra_numbers varchar(20))
returns (
    new_id integer)
as
begin
  INSERT INTO DRAWS (LOTTERY_ID, DRAW_DATE, MAIN_NUMBERS, EXTRA_NUMBERS)
  VALUES (:P_LOTTERY_ID, :P_DRAW_DATE, :P_MAIN_NUMBERS, :P_EXTRA_NUMBERS)
  RETURNING ID INTO :NEW_ID;
  execute procedure add_draw_numbers(:new_id);
  suspend;
end

create or alter procedure update_draw (
    p_draw_id integer,
    p_draw_date date,
    p_main_numbers varchar(50),
    p_extra_numbers varchar(20))
as
begin
  UPDATE DRAWS set
    DRAW_DATE = :p_draw_date,
    MAIN_NUMBERS = :p_main_numbers,
    EXTRA_NUMBERS = :p_extra_numbers
  WHERE
    ID = :p_draw_id;

  DELETE FROM DRAW_NUMBERS WHERE DRAW_ID = :p_draw_id;
  execute procedure add_draw_numbers(:p_draw_id);
end

CREATE TABLE LANGUAGES (
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ISO_CODE VARCHAR(2) NOT NULL,
  LANGUAGE_NAME VARCHAR(20) NOT NULL,
  IS_DEFAULT BOOLEAN DEFAULT FALSE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE
);

ALTER TABLE LANGUAGES ALTER IS_DEFAULT SET DEFAULT FALSE;
ALTER TABLE LANGUAGES ALTER IS_ACTIVE SET DEFAULT TRUE;

INSERT INTO LANGUAGES (ISO_CODE, LANGUAGE_NAME, IS_DEFAULT, IS_ACTIVE)
VALUES ('en', 'English', TRUE, TRUE);

INSERT INTO LANGUAGES (ISO_CODE, LANGUAGE_NAME, IS_DEFAULT)
VALUES ('de', 'Deutsch', FALSE);

INSERT INTO LANGUAGES (ISO_CODE, LANGUAGE_NAME, IS_DEFAULT)
VALUES ('ru', 'Русский', FALSE);

create or alter procedure update_default_language (
  p_language_id integer)
as
begin
  UPDATE languages SET is_default = true WHERE id = :p_language_id;
  UPDATE languages SET is_default = false WHERE id != :p_language_id;
end

create or alter procedure get_single_number_frequency (
    p_lottery_id integer,
    p_start_date date,
    p_end_date date)
returns (
    number smallint,
    frequency integer)
as
begin
  FOR
    SELECT
        dn.number,
        COUNT(*) AS frequency
    FROM DRAW_NUMBERS dn
    JOIN DRAWS d ON dn.draw_id = d.id
    WHERE d.draw_date BETWEEN :p_start_date AND :p_end_date
      AND dn.number_kind = 'main'
    GROUP BY dn.number
    ORDER BY frequency DESC
    INTO :number, :frequency
  DO
    SUSPEND;
end

create or alter procedure get_pair_number_frequency (
    p_lottery_id integer,
    p_start_date date,
    p_end_date date)
returns (
    number1 smallint,
    number2 smallint,
    frequency integer)
as
begin
  for
    select
        dn1.number as number1,
        dn2.number as number2,
        count(*) as frequency
    from draw_numbers dn1
    join draw_numbers dn2
      on dn1.draw_id = dn2.draw_id
     and dn1.number < dn2.number
    join draws d
      on dn1.draw_id = d.id
    where d.lottery_id = :p_lottery_id
      and d.draw_date between :p_start_date and :p_end_date
      and dn1.number_kind = 'main'
      and dn2.number_kind = 'main'
    group by dn1.number, dn2.number
    order by frequency desc
    into :number1, :number2, :frequency
  do
    suspend;
end

create or alter procedure get_triplet_number_frequency (
    p_lottery_id integer,
    p_start_date date,
    p_end_date date
)
returns (
    number1 smallint,
    number2 smallint,
    number3 smallint,
    frequency integer
)
as
begin
  for
    select
        dn1.number as number1,
        dn2.number as number2,
        dn3.number as number3,
        count(*) as frequency
    from draw_numbers dn1
    join draw_numbers dn2
      on dn1.draw_id = dn2.draw_id
     and dn1.number < dn2.number
    join draw_numbers dn3
      on dn1.draw_id = dn3.draw_id
     and dn2.number < dn3.number
    join draws d
      on dn1.draw_id = d.id
    where d.lottery_id = :p_lottery_id
      and d.draw_date between :p_start_date and :p_end_date
      and dn1.number_kind = 'main'
      and dn2.number_kind = 'main'
      and dn3.number_kind = 'main'
    group by dn1.number, dn2.number, dn3.number
    order by frequency desc
    into :number1, :number2, :number3, :frequency
  do
    suspend;
end

create or alter procedure get_extra_number_frequency (
    p_lottery_id integer,
    p_start_date date,
    p_end_date date)
returns (
    number smallint,
    frequency integer)
as
begin
  FOR
    SELECT
      dn.number,
      COUNT(*) AS frequency
    FROM DRAW_NUMBERS dn
    JOIN DRAWS d ON dn.draw_id = d.id
    WHERE
      d.lottery_id = :p_lottery_id
      AND d.draw_date BETWEEN :p_start_date AND :p_end_date
      AND dn.number_kind = 'extra'
    GROUP BY dn.number
    ORDER BY frequency DESC
    INTO :number, :frequency
  DO
    SUSPEND;
end

create or alter procedure get_number_rythm (
    p_lottery_id integer,
    p_start_date date,
    p_end_date date,
    p_number_kind varchar(5))
returns (
    number smallint,
    cnt integer,
    avg_interval numeric(10,2),
    uniformity numeric(10,4))
as
declare variable cur_draw integer;
declare variable last_draw integer;
declare variable interval integer;
declare variable intervals_sum numeric(18,4);
declare variable intervals_cnt integer;
declare variable intervals_sumsq numeric(18,4);
declare variable mean numeric(18,6);
declare variable variance numeric(18,6);
BEGIN
  FOR
    SELECT DISTINCT N.NUMBER
    FROM DRAWS D
    JOIN DRAW_NUMBERS N ON N.DRAW_ID = D.ID
    WHERE D.LOTTERY_ID = :p_lottery_id
      AND D.DRAW_DATE BETWEEN :p_start_date AND :p_end_date
      AND N.NUMBER_KIND = :p_number_kind
    ORDER BY N.NUMBER
    INTO :number
  DO
  BEGIN
    cnt = 0;
    intervals_sum = 0;
    intervals_sumsq = 0;
    intervals_cnt = 0;
    last_draw = NULL;

    FOR
      SELECT D.ID
      FROM DRAWS D
      JOIN DRAW_NUMBERS N ON N.DRAW_ID = D.ID
      WHERE D.LOTTERY_ID = :p_lottery_id
        AND D.DRAW_DATE BETWEEN :p_start_date AND :p_end_date
        AND N.NUMBER_KIND = :p_number_kind
        AND N.NUMBER = :number
      ORDER BY D.ID
      INTO :cur_draw
    DO
    BEGIN
      IF (last_draw IS NULL) THEN
        last_draw = cur_draw;
      ELSE
      BEGIN
        interval = cur_draw - last_draw;
        intervals_sum = intervals_sum + interval;
        intervals_sumsq = intervals_sumsq + (interval * interval);
        intervals_cnt = intervals_cnt + 1;
        last_draw = cur_draw;
      END

      cnt = cnt + 1;
    END

    IF (intervals_cnt > 0) THEN
    BEGIN
      mean = intervals_sum / intervals_cnt;
      variance = (intervals_sumsq / intervals_cnt) - (mean * mean);
      IF (variance < 0) THEN variance = 0;

      avg_interval = CAST(mean AS NUMERIC(10,2));
      uniformity = 1 - (SQRT(variance) / NULLIF(mean, 0));
    END
    ELSE
    BEGIN
      avg_interval = NULL;
      uniformity = NULL;
    END

    SUSPEND;
  END
END