CREATE DATABASE 'D:\LottoMetrics.FDB'
USER 'sysdba' PASSWORD 'masterkey'
PAGE_SIZE 8192
DEFAULT CHARACTER SET UTF8;

CREATE TABLE countries (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name VARCHAR(50) NOT NULL,
    iso_code VARCHAR(2) NOT NULL,
    region VARCHAR(50)
);

INSERT INTO countries (country_name, iso_code, region) VALUES ('Germany', 'DE', 'Europe');

CREATE TABLE lotteries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id INTEGER NOT NULL,
    lottery_name VARCHAR(50) NOT NULL,
    main_count SMALLINT NOT NULL,
    main_start SMALLINT NOT NULL,
    main_finish SMALLINT NOT NULL,
    extra_count SMALLINT DEFAULT 0,
    extra_start SMALLINT DEFAULT 0,
    extra_finish SMALLINT DEFAULT 0,
    CONSTRAINT fk_lottery_country FOREIGN KEY (country_id) REFERENCES countries(id)
);

INSERT INTO lotteries (
    country_id, lottery_name,
    main_count, main_start, main_finish,
    extra_count, extra_start, extra_finish
)
VALUES (1, '6 aus 49', 6, 1, 49, 1, 0, 9);

CREATE TABLE draws (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lottery_id INTEGER NOT NULL,
    draw_date DATE NOT NULL,
    main_numbers VARCHAR(50) NOT NULL,
    extra_numbers VARCHAR(20),
    CONSTRAINT fk_draw_lottery FOREIGN KEY (lottery_id) REFERENCES lotteries(id)
);

CREATE TABLE draw_numbers (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id INTEGER NOT NULL,
    number SMALLINT NOT NULL,
    number_kind VARCHAR(5) NOT NULL,
    CONSTRAINT fk_number_draw FOREIGN KEY (draw_id) REFERENCES draws(id),
    CONSTRAINT chk_number_kind CHECK (number_kind IN ('main', 'extra'))
);

CREATE INDEX idx_draws_date ON draws(draw_date);
CREATE INDEX idx_draws_lottery_id ON draws(lottery_id);
CREATE INDEX idx_draw_numbers_draw_id ON draw_numbers(draw_id);
CREATE INDEX idx_draw_numbers_number ON draw_numbers(number);
CREATE INDEX idx_draw_numbers_number_kind ON draw_numbers(number_kind);

CREATE OR ALTER PROCEDURE fill_draw_numbers
AS
DECLARE VARIABLE v_draw_id INTEGER;
DECLARE VARIABLE v_main_numbers VARCHAR(50);
DECLARE VARIABLE v_extra_numbers VARCHAR(20);
DECLARE VARIABLE v_num VARCHAR(5);
DECLARE VARIABLE v_pos INTEGER;
BEGIN
  FOR SELECT id, main_numbers, extra_numbers
      FROM draws
      INTO :v_draw_id, :v_main_numbers, :v_extra_numbers
  DO
  BEGIN
    WHILE (CHAR_LENGTH(:v_main_numbers) > 0) DO
    BEGIN
      v_pos = POSITION(',' IN :v_main_numbers);
      IF (v_pos > 0) THEN
      BEGIN
        v_num = SUBSTRING(:v_main_numbers FROM 1 FOR v_pos-1);
        v_main_numbers = SUBSTRING(:v_main_numbers FROM v_pos+1);
      END
      ELSE
      BEGIN
        v_num = :v_main_numbers;
        v_main_numbers = '';
      END
      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:v_draw_id, CAST(:v_num AS SMALLINT), 'main');
    END
    IF (:v_extra_numbers IS NOT NULL AND :v_extra_numbers <> '') THEN
    BEGIN
      INSERT INTO draw_numbers(draw_id, number, number_kind)
      VALUES (:v_draw_id, CAST(:v_extra_numbers AS SMALLINT), 'extra');
    END
  END
END